app:
  name: legalify-auth-service
server:
  port: 8081

spring:
  config:
    import: optional:file:.env[.properties]
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: https://korvex.us.auth0.com/
          # The jwk-set-uri is resolved automatically.
          jwk-set-uri: https://korvex.us.auth0.com/.well-known/jwks.json

auth:
  client-id: ${AUTH0_CLIENT_ID}
  client-secret: ${AUTH0_CLIENT_SECRET}
  domain: ${AUTH0_DOMAIN}
  audience: ${AUTH0_AUDIENCE}
